# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://berkayzuhre.github.io/oredata_nbdev/"

git_url = "https://github.com/berkayzuhre/oredata_nbdev/tree/master/"

def custom_doc_links(name): return None
